
name: Deployment job

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      image:
        required: false
        type: string
      target:
        required: true
        type: string
      runner:
        required: false
        default: 'undefined'
        type: string
    secrets:
      token:
        required: true
      dotoken:
        required: false

env:
  IMAGE: ${{ inputs.image }}
  SERVICE: ${{ inputs.service }}
  TARGET: ${{ inputs.target }}

jobs:
  deploy:
    runs-on: ${{ inputs.runner != 'undefined' && inputs.runner || format('{0}-runner', inputs.target) }}
    outputs:
      image: ${{ inputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: vimalsudhanorg/infra
          ref: master
          path: __infra
          token: ${{ secrets.token }}

      - name: Install doctl
        if: ${{ inputs.runner == 'ubuntu:latest' }}
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.dotoken }} 

      - name: Do Deployment
        run: |
          cd $GITHUB_WORKSPACE/__infra
          ./scripts/deploy.sh