
name: Deployment job

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      runner:
        required: false
        default: 'dev-runner'
        type: string

jobs:
  deploy:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Hello
        run: echo "Hello World"
